apiVersion: v1
kind: Service
metadata:
  name: kuber-service-nodeport
spec:
  # externalTrafficPolicy: Local # Направляет запросы только к тем подам, которые есть на ноде, на которую идет подключение
  # sessionAffinity: ClientIP # Перенапраялят запросы с одного клиентского IP строго на 1 pod (кэширование клиентского IP)
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30080
  type: NodePort
