apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-labels
  labels:
    environment: dev
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: gepox/fastapi-simple:0.1.0
      ports:
        - containerPort: 8000
