apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1
    type: Recreate # RollingUpdate # Recreate
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: kuber-app
          image: gepox/fastapi-simple:latest
          ports:
            - containerPort: 8000
