apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-qa-1
  namespace: qa
  labels:
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: gepox/fastapi-simple:0.1.0
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-qa-2
  namespace: qa
  labels:
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: gepox/fastapi-simple:0.1.0
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-dev-1
  namespace: dev
  labels:
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: gepox/fastapi-simple
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-dev-2
  namespace: dev
  labels:
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: gepox/fastapi-simple
      ports:
        - containerPort: 8000
