apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-test
  labels: 
     app: http-server
     environment: test
spec:
  nodeSelector:
    test: "true"
  containers:
  - name: app-kuber-container
    image: gepox/fastapi-simple:0.1.0
    ports:
    - containerPort: 8000