apiVersion: batch/v1
kind: Job
metadata:
  name: pi-completions
spec:
  completions: 3
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
