apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: gepox/fastapi-simple
      name: test-container
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /data
        # this field is optional
        type: Directory
